### ISSUE TITLE
Request - Force Full fuel reserve

### ISSUE THREAD

**Issue by WarezCrawler** [jrbudda/KerbalEngineer#13]
I have a request for a feature. 

I'm playing with resources that can only be mined on other planets and used for fuel. This results in my new vessels does not have that fuel in editor, thus being impossible to get a reading on.
Would it be possible to force the calculation to act as if that resource was available? I'm thinking for specific resources.

I'm thinking to accept that it will be imperfect, like not trying to calculated the mass changes and stuff, but just assume enough is available. this would also help with special engines the uses Air/atm as "fuel" that affects ISP.

Right now. I'm building those in blind, or doing calculations by hand....

**Comment by jrbudda** [comment]
What mod is this?

**Comment by WarezCrawler** [comment]
KarbonitePlus + MFT

Example:
// Karbonite MFT|RF support
@TANK_DEFINITION[Default]:FOR[KarbonitePlus]:NEEDS[modularFuelTanks|RealFuels]
{
    TANK
    {
        name = Karborundum
        cost = 2000
        amount = 0.0
        maxAmount = 0.0
        **fillable = false**
    }
}

I've also observed with KFD-125 Karborundum Fusion Drive [KA_Engine_125_02] that the electricity it needs blocks for delta-v calculation. Probably because it is mass less and needed for ISP.

**Comment by WarezCrawler** [comment]
I also believe that "The Spice" mod has resources that can only be collected on Duna.

**Comment by jrbudda** [comment]
Hmm OK so there's 2 ways to approach this, fix this in KER or fix it in MFT. The more elegant solution would be to fix it in MFT, allowing you to set tank amounts in the VAB for simulation purposes and forcing them empty when launching the ship. That way you get precise control on a tank by tank basis not just for KER but things like stock CoM calculations. 

If I fix it in KER all you get is a little hidden button somewhere in the settings menu where it assumes all tank resources = their capacity, which isn't going to give accurate results anyway since you'll burn fuel, etc, getting to your mining location.

So I think I would prefer you take this up with the MFT/RF guys and see if they'll fix it on their end, and only 
if they won't, I work something into KER.

**Comment by WarezCrawler** [comment]
"Fixing in MFT" would require it to be done in it's dll, right? This would not apply a solution to the case where a resource in general is limited to being harvested offworld, but only for MFT.

But I'm not entirely put off by en core idea of your suggestion. A mod that temporarily fills all tanks that normally cannot be changed in VAB/SPH in order to get a dv reading.

I guess that could be done. And maybe the most natural place to have that is not in KER.

I will close this, and maybe look into doing this in my mod. My main issue is the UI part. Never mastered that beyond right click menus.

**Comment by jrbudda** [comment]
You wont be able to make a mod that fills the tanks. The way MFT is coded every GUI 'update' any unfillable tank is forced to 0 resources, that's how they're made 'unfillable'. This is not a stock concept but just how MFT does it. I didn't look into The Spice but assume it's similar.

I will open a suggestion for this on the MFT github.

**Comment by WarezCrawler** [comment]
I have no clue of the mechanics of MFT, but in the resource definition there is a setting
"isTweakable = false"
This one prevents you from manipulating with the contents of a tank in the VAB. Combine this with setting the resource "amount = 0" in the parts effectively gives you a resource, that you can use, but not add in editor. Then you can harvest it offworld. 
I believe this is how the spice does things, and I have had a personal mod for years doing this for Karborundum, and other stuff in order to make the game harder, while having really powerful scifi propulsion possibilities.

**Comment by jrbudda** [comment]
OK hold on. I'm confused. I just actually loaded up the combination of mods you mentioned and have no problem seeing dV in the VAB using karboroundum engines.

![image](https://user-images.githubusercontent.com/1927235/40137322-16f5bd1c-5918-11e8-82bf-7d61bf01bb1c.png)

What exactly is the problem here?

**Comment by jrbudda** [comment]
The Spice works as well. You can fill spice tanks in the VAB all you want, when you go to launch if you don't have the actual resource available it empties the tank.

**Comment by WarezCrawler** [comment]
I must have missed something. Sorry to have wasted your time... I will look into this issue further. I do have 70+ mods installed, so it can take a while.
Thanks for your time.
